CREATE TABLE IF NOT EXISTS %%BOARD%% ( 
  doc_id int unsigned NOT NULL auto_increment, 
  media_id int unsigned NOT NULL DEFAULT '0', 
  id decimal(39,0) unsigned NOT NULL DEFAULT '0', 
  num int unsigned NOT NULL, 
  subnum int unsigned NOT NULL, 
  parent int unsigned NOT NULL DEFAULT '0', 
  timestamp int unsigned NOT NULL, 
  preview varchar(20), 
  preview_w smallint unsigned NOT NULL DEFAULT '0', 
  preview_h smallint unsigned NOT NULL DEFAULT '0', 
  media text, 
  media_w smallint unsigned NOT NULL DEFAULT '0', 
  media_h smallint unsigned NOT NULL DEFAULT '0', 
  media_size int unsigned NOT NULL DEFAULT '0', 
  media_hash varchar(25), 
  media_filename varchar(20), 
  spoiler bool NOT NULL DEFAULT '0', 
  deleted bool NOT NULL DEFAULT '0', 
  capcode enum('N', 'M', 'A', 'G') NOT NULL DEFAULT 'N', 
  email varchar(100), 
  name varchar(100), 
  trip varchar(25), 
  title varchar(100), 
  comment text,
  delpass tinytext, 
  sticky bool NOT NULL DEFAULT '0', 
  
  PRIMARY KEY (doc_id), 
  UNIQUE num_subnum_index (num, subnum), 
  INDEX id_index(id),
  INDEX media_id_index(media_id),
  INDEX num_index(num), 
  INDEX subnum_index(subnum),
  INDEX parent_index(parent),
  INDEX timestamp_index(timestamp),
  INDEX media_hash_index(media_hash),
  INDEX media_filename_index(media_filename),
  INDEX email_index(email),
  INDEX name_index(name),
  INDEX trip_index(trip),
  INDEX fullname_index(name,trip)
) engine=InnoDB CHARSET=%%CHARSET%%;